In [2]:
import pandas as pd
import numpy as np

In [3]:
# 데이터를 분석하려면 데이터프레임 형태로 만들면 됨.
# 행(인스턴스, 실제값), 열(속성, 특성)을 가지는 2차원이 되게 됨.
# 파이썬에서는 데이터분석시 사용하는 2차원을 다루기 위해서 클래스(부품)을 만들었음.

In [5]:
dics = {"name":["홍길동","박길동","김길동","송길동"], "age":[10,20,30,40]}
df = pd.DataFrame(dics)
df

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [6]:
# 인덱스가 자동증가해서 붙어있는 부품: 데이터프레임
df.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
type(df.index) #RangeIndex 부품, class

pandas.core.indexes.range.RangeIndex

In [9]:
df.name # 시리즈는 작은 데이터프레임

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [25]:
# 시리즈를 데이터프레임으로 변경할 수 있다.
df_name = df['name'].to_frame()
df_name
type(df_name)

pandas.core.frame.DataFrame

In [10]:
df['name']

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [12]:
df.index = df.index.tolist() #인덱스만 목록을 가지고 오고 싶으면 list로 변경해서 사용
df.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [13]:
type(df['name'])

pandas.core.series.Series

In [14]:
# 데이터프레임은 RangeIndex, Series의 결합임
# 시리즈는 인덱스와 리스트의 결합

In [15]:
df['name'].index

Int64Index([0, 1, 2, 3], dtype='int64')

In [20]:
df_name_list = df['name'].index.tolist()
df_name_list

[0, 1, 2, 3]

In [21]:
type(df_name_list)

list

In [17]:
df['name'].values

array(['홍길동', '박길동', '김길동', '송길동'], dtype=object)

In [18]:
type(df['name'].values)

numpy.ndarray

In [19]:
df_name_values = df['name'].values.tolist()
df_name_values

['홍길동', '박길동', '김길동', '송길동']

# 데이터프레임 사용방법
## dict 사용
### csv, excel 파일 읽어오기
### df에 values, column을 지정

In [22]:
df2 = pd.DataFrame(data=[['홍길동', 100], ['김길동',200]], columns=['name', 'age'])
df2

name  age
0  홍길동  100
1  김길동  200

In [23]:
name_values = ["홍길동","박길동","김길동","송길동"]
age_values = [10,20,30,40]

df2 = pd.DataFrame({"name":name_values, "age":age_values})
df2

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [26]:
type(df2.columns)

pandas.core.indexes.base.Index

In [27]:
df2.columns

Index(['name', 'age'], dtype='object')

In [28]:
df2.columns.tolist()

['name', 'age']

In [29]:
data = [100, 200, 300] # 1차원인 리스트
sum(data)

600

In [30]:
max(data)

300

In [31]:
min(data)

100

In [32]:
# ndarray: 다양한 차원의 데이터(배열)를 하나의 클래스로 다루기위해서 만들어졌음.
# n: 숫자
# d: dimension, 차원
# array: 배열

In [35]:
arr1 = np.arange(15) #0~14까지의 연속된 값을 만들어주는 함수, 1차원
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr1_reshape = arr1.reshape(3, 5) #원하는 차원으로(모양으로) 변환
arr1_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
type(arr1_reshape)

numpy.ndarray

In [42]:
# mask
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [43]:
mask2 = np.zeros((3, 4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
arr2 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr3 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [50]:
# 행렬의 연산을 할 수 있음.
arr2 * arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [51]:
arr2 - arr3

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [52]:
np.random.rand(20)

array([0.6262463 , 0.98883402, 0.32071009, 0.66060734, 0.99104841,
       0.17726209, 0.65182241, 0.36710179, 0.2969241 , 0.79178724,
       0.22426497, 0.12018403, 0.15656   , 0.6696134 , 0.18767191,
       0.14018213, 0.51061857, 0.17639449, 0.34794649, 0.98293008])

In [53]:
np.random.randint(10)

2